import { useState, useEffect } from 'react';

// 1. Define what an Item looks like (Type Safety)
interface Item {
  id: number;
  name: string;
  description: string | null;
  price: number;
  is_active: boolean;
}

function App() {
  // 2. State Management
  const [items, setItems] = useState<Item[]>([]);
  const [status, setStatus] = useState<string>("System Idle");

  // 3. Load Data (GET Request)
  useEffect(() => {
    const fetchData = async () => {
      try {
        setStatus("Fetching Data...");
        const res = await fetch("http://127.0.0.1:8000/items/");
        const data = await res.json();
        setItems(data);
        setStatus("System Online");
      } catch (error) {
        console.error(error);
        setStatus("Connection Error");
      }
    };

    fetchData();
  }, []);

  // 4. Create Data (POST Request)
  const handleTestPost = async () => {
    try {
      const response = await fetch("http://127.0.0.1:8000/items/", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          name: `Test Item ${new Date().toLocaleTimeString()}`,
          description: "Generated by Neural Link Test",
          price: 10,
          is_active: true
        })
      });

      if (response.ok) {
        const newItem = await response.json();
        setItems([...items, newItem]); // Add to list instantly
      }
    } catch (error) {
      console.error("Post failed:", error);
    }
  };

  // 5. Render the UI
  return (
    <div className="min-h-screen bg-empire-black text-tatooine-sand font-mono p-8">
      
      <div className="max-w-2xl mx-auto border border-hologram-blue/30 p-6 rounded bg-gray-900/50">
        
        {/* Header */}
        <div className="flex justify-between items-center mb-6 border-b border-gray-700 pb-4">
          <h1 className="text-2xl text-hologram-blue uppercase tracking-widest">Hololab v1.0</h1>
          <span className="text-xs text-gray-500 uppercase">{status}</span>
        </div>

        {/* Test Action */}
        <div className="mb-6 text-right">
          <button 
            onClick={handleTestPost}
            className="bg-hologram-blue/10 text-hologram-blue border border-hologram-blue px-4 py-2 rounded text-xs uppercase hover:bg-hologram-blue hover:text-black transition-colors"
          >
            + Run Connection Test
          </button>
        </div>

        {/* Data Display */}
        <div className="space-y-2">
          {items.length === 0 && <p className="text-gray-600 text-center">No items found.</p>}
          
          {items.map((item) => (
            <div key={item.id} className="flex justify-between p-3 border border-gray-800 bg-black rounded hover:border-hologram-blue/50">
              <div>
                <span className="block font-bold text-white">{item.name}</span>
                <span className="text-xs text-gray-500">{item.description}</span>
              </div>
              <span className="text-hologram-blue">{item.price} cr</span>
            </div>
          ))}
        </div>

      </div>
    </div>
  );
}

export default App;